# Generated by Django 4.2.7 on 2023-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='camada',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='post',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(default='Título por defecto', max_length=100),
        ),
    ]
