# Generated by Django 4.2.7 on 2023-12-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0005_remove_perfil_usuario_remove_post_autor_curso_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/post'),
        ),
    ]
